### ISSUE TITLE
Configure state value to not include 

### ISSUE THREAD

**Issue by dinki** [jeffc/hassmic-integration#3]
Can you consider changing the _state device from:

```wake_word-start```

 to something without start in the name  like :
```
wake_word-listening
```
This simple change should allow for View Assist dashboard to be changed only slightly to allow for the visual 'listening' bar to be shown for users using hassmic.

**Comment by jeffc** [comment]
@dinki - I added a `simple_state` sensor in c7f8847 that can take the following values (all of the form `"stage-status"`):

 * `wake_word-listening` - hassmic is listening for the wake word
 * `stt-listening` - the wakeword was heard and we're now listening for the prompt
 * `intent-processing` - done listening for the prompt, now processing
 * `tts-generating` - The intent has been processed, and now we're generating speech
 * `tts-speaking` - The speech has been generated and sent to the media player
 * `error-error` - an error has occured

As written, we only stay in the `tts-speaking` phase very briefly, since the pipeline doesn't wait for the speech to finish speaking before it starts listening again.

**Comment by dinki** [comment]
This is working great with View Assist.  Thank you for including.  Closing this issue.
